### ISSUE TITLE
argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by lx0741** [jipegit/OSXAuditor#20]
[INFO] Users' LoginItems
[INFO] lx0741 LoginItems
[INFO] /Users/lx0741/Library/Preferences/com.apple.loginitems.plist
[INFO] Cannot parse /Users/lx0741/Library/Preferences/com.apple.loginitems.plist (Binary or JSON plist may FAIL) 

Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1651, in Main
    ParseStartup()
  File "osxauditor.py", line 550, in ParseStartup
    if "SessionItems" in LoginItemsPlist:
TypeError: argument of type 'bool' is not iterable

**Comment by jipegit** [comment]
Fixed.
