### ISSUE TITLE
AggregateLogs combines file path incorrectly

### ISSUE THREAD

**Issue by superponible** [jipegit/OSXAuditor#36]
Receive the error when running with -z ../TEMP:

    [INFO] Log files aggregation
    [INFO] All log files are aggregated in ../TEMP/OSXAuditor_report_/HOSTNAME/_/20140916-160436/.zip
    [INFO] Log files aggregation FAILED (2, 'No such file or directory')

Each argument in the function is joined with the system path delimiter (/ in OSX's case) in this call:

    ZipLogsFilePath = os.path.join(ZipLogsFile, "OSXAuditor_report_", HOSTNAME, "_", time.strftime("%Y%m%d-%H%M%S", time.gmtime()), ".zip")

Change the commas to + like this:

    ZipLogsFilePath = os.path.join(ZipLogsFile, "OSXAuditor_report_" + HOSTNAME + "_" + time.strftime("%Y%m%d-%H%M%S", time.gmtime()) + ".zip")

**Comment by jipegit** [comment]
Fixed, thanks.
